# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Md CI

on:
  push:
    tags:
      - md**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8.7.0
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run md build
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: 'packages/vtron-md/docs/.vitepress/dist/'
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.DEPLOY_REMOTE_MD_DIR }}
    # - name: Axios Request
    #   # You may pin to the exact commit or the version.
    #   # uses: potaesm/github-actions-request@7c5145f0b707e9a1d7b7e71cf1812fcec2228fb5
    #   uses: potaesm/github-actions-request@1.0.7
    #   with:
    #     # `url` is the server URL that will be used for the request
    #     url: ${{ secrets.REQUEST_URI }}${{ github.repository }}:${{ job.status }}
    #     # `method` is the request method to be used when making the request
    #     method: get
